### ISSUE TITLE
Local domain set-up

### ISSUE THREAD

**Issue by pyronaur** [BrowserSync/browser-sync#122]
Hey there,
I'm using a little funky setup and I'm hoping you can help me.

I'm using 0.7.2 BrowserSync with Grunt ( moving to Gulp soon ) on a Mac with a MAMP Pro. 
Instead of using "virtual domains" for my MAMP, I'm using a real one ( in this case: "km.localbox.in" ). Every now and then, when my local IP changes ( the IP from the router that is) I run a small script that updates the IP for me on easyDNS.com ( I should probably write an article about that, it's quite useful I think ). 

That way I always have easy-access from all the devices connected to the same router ( not only Bonjour enabled devices ). In addition - I can give each project a full-separate domain, instead of me.local/~something or so.

So basically - what I want - is to have BrowserSync connect properly and stay with km.localbox.in instead of jumping to 192.168.0.100

My current config is:

```
        browserSync:
            sync:
                bsFiles: 
                    src: ["js/*.js", "**/*.php", "css/*.css", "images/**/*.{png,jpg,jpeg,gif,webp,svg}"]
                options:
                    proxy: "km.localbox.in"
                    # host: "km.localbox.in"    
                    watchTask: true
                    ghostMode:
                        clicks: false
                        scroll: false
                        links: true
                        forms: true
```

I have also tried to uncomment the "host" part, but when I do that, I get an "io not found" error in my dev console and nothing works at all. 

With my current setup BrowserSync is somewhat unpredictable. Sometimes it masks the links, sometimes it doesn't and I have no idea what's going and if my setup is correct...
